### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by davej** [sholladay/os-proxy#2]
v0.2.0 is not published to npm. v0.1.0 is not compatible with latest node versions.

**Comment by sholladay** [comment]
Hi @davej, thanks for your interest in this project. I will publish the latest to npm sometime this week. Pending just a bit more manual testing, since I don't have automated tests set up here yet.

**Comment by sholladay** [comment]
`0.2.0` is now live on npm and so is a `0.2.1` with a bit of housekeeping

**Comment by davej** [comment]
:+1:
